# Generated by Django 2.1.7 on 2019-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='积分余额'),
        ),
    ]
